for i=1:1
    for j=1
        main('-algorithm',@ROIDWUmoea, ...
            '-problem',@WFG9, ...
            '-N',100, ...
            '-M',2, ...
            '-D',2*j+3, ...
            '-evaluation',1e5, ...
            '-save',1, ...
            '-run',i)
    end
end